### ISSUE TITLE
ipad Share does not work

### ISSUE THREAD

**Issue by mani144** [Shin-NiL/Godot-Share#10]
i searched on the internet about this problem and i found many people are facing it , 
the problem is :

*** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIActivityViewController (<UIActivityViewController: 0x107acd200>). In its current trait environment, the modalPresentationStyle of a UIActivityViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'

the solution :

https://stackoverflow.com/questions/25644054/uiactivityviewcontroller-crashing-on-ios-8-ipads
https://medium.com/@dushyant_db/how-to-present-uiactivityviewcontroller-on-iphone-and-ipad-ae72013d2a5a

**Comment by mani144** [comment]
#11 i fixed the problem in this pull request

**Comment by Shin-NiL** [comment]
Thank you very much!
