### ISSUE TITLE
Help with implementing a IAP module on IOS

### ISSUE THREAD

**Issue by Valeryn4** [Shin-NiL/Godot-Share#12]
Sorry to write here, I could not find your contacts. Mail or Telegram
[I made such a module](https://github.com/Valeryn4/Godot-IOS-Services-Extend-Module/tree/dev) (see dev branch). I tried to implement the [promoted purchases](https://developer.apple.com/app-store/promoting-in-app-purchases/).

But I have no way to test it. And the knowledge of the Objective-C language is very weak.
Could you help or suggest who could?

[My IAP](https://github.com/Valeryn4/Godot-IOS-Services-Extend-Module/tree/dev)

**Comment by Shin-NiL** [comment]
I'm sorry, but I don't have any Apple hardware and/or knowlegde enough to help you. This module was made long time ago when I've borrowed a Mac Mini.

**Comment by Valeryn4** [comment]
Can you tell me who can help me?
I have to code in NotePad and test remotely once a week. :(

By the way, version 1.0 is already working with promoted purchases)

**Comment by Shin-NiL** [comment]
I could not find anybody to help me either, sorry.
