### ISSUE TITLE
iOS recognize the module but doesn't show

### ISSUE THREAD

**Issue by cemeai** [Shin-NiL/Godot-Share#15]
I am trying to try this module for iOS I was able to create the build no errors. I included the code in my game. 

`func _ready():
	if Engine.has_singleton("GodotShare"):
		print('share prepared')
		share = Engine.get_singleton("GodotShare")

func _on_ShareBtn_pressed():
	#friendPopup.visible = false	
	if (share != null):
		print('sharing')
		share.hareText('Friend Code', 'FC', 'A93DK9L')`

When I run the game on my phone I get the messages in console

`2020-06-15 14:07:56.848227-0500 Game[1407:4599503] share prepared
2020-06-15 14:08:00.808297-0500 Game[1407:4599503] sharing`

But the phone doesn't seem to prompt me anything, is there anything i am missing?

**Comment by Shin-NiL** [comment]
I'm sorry, I don't have any Apple hardware anymore, so I can't help. I hope somebody in the community ca do.
