### ISSUE TITLE
Is it possiable to get the result of the share action?

### ISSUE THREAD

**Issue by Geequlim** [Shin-NiL/Godot-Share#2]
For example I want to give players some rewards to encourage them to share the game.

```gdscript
share.connect("share_done", self, "give_some_reward")
```

**Comment by Shin-NiL** [comment]
Yes, I think it's is possible to be implemented. We won't be able to use signals to connect though, as it doesn't work with Android, so we have to use callbacks, something like this:

```gdscript
func _on_share_result(success):
	if success:
		give_some_reward()
```

This way it should work on both platforms (Android & iOS).

**Comment by Shin-NiL** [comment]
As a result of my research, I've discovered that there is no reliable way to return whether the data was shared or not.

Using Android's onActivityResult depends on each app (Twitter, Gmail, Telegram, etc.) to send the signal of completeness of the action and this varies greatly. By testing I did half of them report this value as expected. So I will not implement this feature for now.
