### ISSUE TITLE
Compiling for Android

### ISSUE THREAD

**Issue by ghost** [Shin-NiL/Godot-Share#4]
I tried several times with different versions of the required tools to compile the godot source code so I got a release and debug apk. I succeed the compiling, but the result gives me a way smaller file than the original. Also when I exported my android app, on startup I got short a black screen and than the app crashed. 

If you have experience with this issue could you tell me how to fix it. Otherwise (worst case) could you compile this (I don't mind in what godot version you compile it, I'm flexible)?

**Comment by Shin-NiL** [comment]
Are you able to compile the Android template without this module?

**Comment by ghost** [comment]
I'm able to compile it but this also gives a much smaller file than the original one godot has in Godot\templates\3.0.6.stable. So I know it isn't your module his fault. But I'm desperate, I asked the godot community on discord but got no replies. Also another guy from 2 years ago with the same issue didn't replied back, so you are my last hope.

**Comment by Shin-NiL** [comment]
Are both (release and debug) apk the same size? What size is "small"?
Are you following these [docs](https://docs.godotengine.org/en/3.0/development/compiling/compiling_for_android.html)?

**Comment by ghost** [comment]
I fixed the crash issue, I uninstalled all my android studio related files and reinstalled it. Now I'm able to compile the template with and without your module, and the exported app doesn't crash. The only problem now remains that the textshare function doesn't got triggered somehow. But first I will search to solve this new issue at my own. When my app crashed the template files sizes were 805 kB (debug) and 18 856 kB (release). Now they are 12 815 kB (debug) and 10 072 kB (release).

**Comment by ghost** [comment]
I tried today the whole day (with debugging enabled, armv7, armv8, more unusefull android stuff installed, etc) but I still couldn't let it work, I switched over to your demo godot share project. So I was sure it wasn't something about my code. But sadly I couldn't even let this work. So I guess I'm not able to compile those templates at my own (atm). 

I saw you had a compiled templates available on your blog (heyzap). But reading the comments, this is a bit outdated bcs you only continue with admod. If I had a working template example I could try to replicate it and so I know my compiling process is right (working). So my only option now is asking you for compiling those templates. I would be very grateful to you.

**Comment by Shin-NiL** [comment]
Which modules do you need in your template? Just this one?

**Comment by ghost** [comment]
Just this one. As soon I got those working templates I'm gonna try to compile my source again to get the same templates as the one you gonna sent me. So I am able to compile it myself in the future.

**Comment by Shin-NiL** [comment]
I've added the compiled template [here](https://github.com/Shin-NiL/Godot-Share/releases/tag/04-02-2019).

**Comment by ghost** [comment]
Thank you, this works. I'm able to share within my app now.
And also thank you for your effort and time.

**Comment by Shin-NiL** [comment]
Nice, you're welcome.
