### ISSUE TITLE
Unable to run in iOS? getting errors

### ISSUE THREAD

**Issue by atologist-pratik** [Shin-NiL/Godot-Share#7]
I'm using godot 3.1 and i download latest godot source code from [Link](https://github.com/godotengine/godot).

Then i follow the steps:

1. Copy **share** folder to **godot/modules** folder.

2. Then i compile for iOS using this [Link](http://docs.godotengine.org/en/stable/development/compiling/compiling_for_ios.html). I used following command to compile.

    ```
    scons p=iphone tools=no target=debug arch=arm
    scons p=iphone tools=no target=debug arch=arm64
    ```
In **godot/bin** i get as result two files :
> libgodot.iphone.debug.arm.a

> libgodot.iphone.debug.arm64.a

3. After i used following command to generate ***.debug.fat.a** file.

```
lipo -create bin/libgodot.iphone.debug.arm64.a bin/libgodot.iphone.debug.arm.a -output bin/libgodot.iphone.debug.fat.a
```
as result i get **libgodot.iphone.debug.fat.a** file in **godot/bin** folder.

4. i replaced **libgodot.iphone.debug.fat.a** file into **godot/misc/dist/ios_xcode** folder

5. i copied **ios_xcode** folder in documents, rename **ios_xcode** to **iphone**, then **zip** it. i get result file **iphone.zip** in Document folder.

6. Then i add iphone.zip file to `Project>Export>Options>Custom Package>Debug`

   [https://imgur.com/9rV78v7](https://imgur.com/9rV78v7)

7. Then Export project.

### Error:

````
Undefined symbols for architecture armv7:
  "_z_verbose", referenced from:
      _inflateInit2_ in FBLogin.a(ftgzip.iphone.debug.arm.o)
      _inflate in FBLogin.a(ftgzip.iphone.debug.arm.o)
      _inflateEnd in FBLogin.a(ftgzip.iphone.debug.arm.o)
      _inflateReset in FBLogin.a(ftgzip.iphone.debug.arm.o)
      _inflate_blocks_reset in FBLogin.a(ftgzip.iphone.debug.arm.o)
      _inflate_codes_free in FBLogin.a(ftgzip.iphone.debug.arm.o)
      _inflate_blocks_new in FBLogin.a(ftgzip.iphone.debug.arm.o)
      ...
  "_z_error", referenced from:
      _inflate_codes in FBLogin.a(ftgzip.iphone.debug.arm.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

````

Can you help me with this? What i'm doing wrong?

xcode 10.1 used with developer account and running in device.

**Comment by Shin-NiL** [comment]
It seems fine to me, but as I don't have an Mac OS to try by myself, I can't confirm it.
Are you able to build and run your custom template without the share module? If not you should open this question on the Godot respository instead.

**Comment by atologist-pratik** [comment]
Well i create custom template without **share module**.  I used below commands to generate binary for debug and release.

```
scons p=iphone tools=no bits=32 target=release arch=arm
scons p=iphone tools=no bits=64 target=release arch=arm64

lipo -create bin/libgodot.iphone.opt.arm64.a bin/libgodot.iphone.opt.arm.a -output bin/libgodot.iphone.release.fat.a


scons p=iphone tools=no bits=32 target=debug arch=arm
scons p=iphone tools=no bits=64 target=debug arch=arm64

lipo -create bin/libgodot.iphone.debug.arm64.a bin/libgodot.iphone.debug.arm.a -output bin/libgodot.iphone.debug.fat.a

```
as result i get **libgodot.iphone.debug.fat.a** and **libgodot.iphone.release.fat.a** in godot/bin folder.

i replace this file with **godot/misc/dist/ios_xcode** files. rename ios_xcode to iphone, then zip it.

Then i replace **iphone.zip** with **/Library/Application\ Support/Godot/templates/3.1.stable**

Then i export project then try to run in device. i get exact same issue.

```
Undefined symbols for architecture arm64:
  "_z_error", referenced from:
      _inflate_codes in FBLogin.a(ftgzip.iphone.debug.arm64.o)
  "_z_verbose", referenced from:
      _inflateInit2_ in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflate in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflateEnd in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflateReset in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflate_blocks_reset in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflate_codes_free in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      _inflate_blocks_new in FBLogin.a(ftgzip.iphone.debug.arm64.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by Shin-NiL** [comment]
So it's an issue related to the engine building process. I recommend that you ask for help on the Godot official channels (QA, github, IRC or Discord).

**Comment by atologist-pratik** [comment]
@Shin-NiL  i finally able to resolve above issue and manage to implement sharing option in iOS.
Here is the link how i compile share module and generate binary for iOS. i'm also adding compiled binary for testing in iOS.

> [https://github.com/atologist-pratik/CustomBuildForGodot](https://github.com/atologist-pratik/CustomBuildForGodot).

**Comment by Shin-NiL** [comment]
Nice, thank you!
