### ISSUE TITLE
Compiling for Android issues

### ISSUE THREAD

**Issue by ATOshailesh** [Shin-NiL/Godot-Share#8]
I'm using godot 3.1 and i download latest godot source code.

Drop the "share" directory inside the "modules" directory on the Godot source.

after compile godot_master code

![Screen Shot 2019-05-13 at 12 11 25 PM](https://user-images.githubusercontent.com/50569018/57600777-63a82500-7578-11e9-873f-41a80f580678.png)

Can you help me with this? What i'm doing wrong?

**Comment by Shin-NiL** [comment]
Are you compiling 3.1.0-stable or master?

**Comment by ATOshailesh** [comment]
Thanks shin-nil,
I resolve this issues.
I used master so get this issues,
3.1.0 stable version fine work.
